# experiment configs
experiment_name: "debug-surreal"

# basic configs
batchsize: 5
n_epochs: 100
seed: 0

video_length: 16
image_size: 64

log_dir: "result/surreal"
tensorboard_dir: "result/surreal/runs"

# interval
log_interval:         10
log_samples_interval: 10
snapshot_interval:    5000
evaluation_interval:  60000

# dataset configs
dataset:
  name: "surreal"
  path: "data/raw/surreal"
  n_workers: 1
  number_limit: -1
  cond: "segm"
  channel: 26
  # cond: "depth"
  # channel: 1

# model configs
gen:
  dim_z_content: 40
  dim_z_motion: 10
  dim_z_color: 10
  ngf: 64
  optimizer:
    lr: 0.0002
    decay: 0.00001
idis: 
  use_noise: True
  noise_sigma: 0.2
  ndf: 32
  optimizer:
    lr: 0.0002
    decay: 0.00001
vdis: 
  use_noise: True
  noise_sigma: 0.2
  ndf: 32
  optimizer:
    lr: 0.0002
    decay: 0.00001
