# experiment configs
log_dir: "result/mug"
experiment_name: "debug"

# basic configs
batchsize: 2
n_epochs: 50000
seed: 0

video_length: 16
image_size: 64
tensorboard_dir: "result/mug/runs"

# interval
log_interval:         5
log_samples_interval: 5
snapshot_interval:    5
evaluation_interval:  5

# dataset configs
dataset: 
  name: "mug"
  path: "data/raw/mug"
  n_workers: 1
  number_limit: 110

# model configs
gen:
  dim_z_content: 40
  dim_z_motion: 10
  dim_z_color: 10
  ngf: 64
  optimizer:
    lr: 0.0002
    decay: 0.00001

idis:
  # TODO: noise sigma schedule
  use_noise: True
  noise_sigma: 0.1
  ndf: 64
  optimizer:
    lr: 0.0002
    decay: 0.00001

vdis:

  use_noise: True
  noise_sigma: 0.1
  ndf: 32
  optimizer:
    lr: 0.0002
    decay: 0.00001
