# experiment configs
experiment_name: "debug-surreal-depth"

# basic configs
batchsize: 2
n_epochs: 50000
seed: 10

video_length: 16
image_size: 64

tensorboard_dir: "result/debug/runs"
log_dir: "result/debug"

# geometric information type
geometric_info:
  name: "segmentation"
  channel: 25

# interval
log_interval:         2
log_samples_interval: 2
snapshot_interval:    5
evaluation_interval:  5

# loss
loss: "adversarial-loss"

# update ratio
num_gen_update: 1
num_dis_update: 1

# dataset configs
dataset:
  name: "surreal"
  path: "data/raw/surreal"
  n_workers: 2
  number_limit: 100

# model evaluation during training using inception score
evaluation:
  batchsize: 50
  num_samples: 200
  metrics: ["is", "fid"]

# model configs
ggen:
  dim_z_content: 40
  dim_z_motion: 10
  ngf: 64
  optimizer:
    lr: 0.0002
    decay: 0.00001

cgen:
  dim_z_color: 10
  ngf: 64
  optimizer:
    lr: 0.0002
    decay: 0.00001

idis:
  use_noise: True
  noise_sigma: 0.2
  ndf: 64
  optimizer:
    lr: 0.0002
    decay: 0.00001

vdis:
  use_noise: True
  noise_sigma: 0.2
  ndf: 32
  optimizer:
    lr: 0.0002
    decay: 0.00001
