# experiment configs
experiment_name: "isogd-depth"

# basic configs
batchsize: 70
n_epochs: 200
seed: 15

video_length: 16
image_size: 64

tensorboard_dir: "result/isogd/runs"
log_dir: "result/isogd"

# geometric information type
geometric_info: "depth"

# interval
log_interval:         160
log_samples_interval: 1200
snapshot_interval:    1200
evaluation_interval:  1200

# training settings
dis_update_ratio: 1 # number of D updates per every G update

# dataset configs
dataset:
  name: "isogd"
  path: "data/raw/isogd"
  n_workers: 8
  number_limit: -1

# model evaluation during training using inception score
evaluation:
  batchsize: 50
  num_samples: 10000

# model configs
ggen:
  dim_z_content: 40
  dim_z_motion: 10
  ngf: 64

  optimizer:
    lr: 0.0002
    decay: 0.00001

cgen:
  dim_z_color: 10
  ngf: 64

  optimizer:
    lr: 0.0002
    decay: 0.00001

idis:
  use_noise: True
  noise_sigma: 0.1
  ndf: 64

  optimizer:
    lr: 0.0005
    decay: 0.00001

vdis:
  use_noise: True
  noise_sigma: 0.1
  ndf: 64

  optimizer:
    lr: 0.0005
    decay: 0.00001
