name: Run test codes

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: run image
      env:
        SHA: ${{ github.sha }}
      run: docker run --rm dcvgan:cpu python -m unittest discover -s src -p '*_test.py'

