name: Run test codes

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: build image
      env:
        SHA: ${{ github.sha }}
      run: docker build . -f Dockerfile.cpu --tag dcvgan.cpu:${SHA}

    - name: run image
      env:
        SHA: ${{ github.sha }}
      run: docker run --rm --name test-dcvgan dcvgan.cpu:${SHA} python -m unittest discover -s src -p '*_test.py'

